### PR TITLE
Add new rooflines

### PR DESCRIPTION
**Pull request by JoseSantosAMD**

### CODE REVIEW

**Comment by maartenarnst** [comment]
Just a question out of curiosity. Why are the rooflines provided as binaries? I would argue it could/would be of interest and of value to users/researchers to see the source code and see how these rooflines are obtained.

**Comment by feizheng10** [comment]
> Just a question out of curiosity. Why are the rooflines provided as binaries? I would argue it could/would be of interest and of value to users/researchers to see the source code and see how these rooflines are obtained.

The binary is only for measuring the peak BW on  each hierarchical level. It is "debatable" open source or not:)
The arithmetic part is open source.

**Comment by coleramos425** [comment]
> The binary is only for measuring the peak BW on each hierarchical level. It is "debatable" open source or not:)
> The arithmetic part is open source.

That's right. The source code for the roofline binary reveals microarchitectural details that our hardware team has not signed off on. @maartenarnst we'll be sure to update you if that changes in the future. As Fei mentioned, the derivation for AI (arithmetic intensity) calculation is open-source if that's of any value:

https://github.com/AMDResearch/omniperf/blob/b9e474ec5ff6afcb3ebafc653dcb475acd7096d0/src/omniperf_analyze/utils/roofline_calc.py#L188

**Review by coleramos425 — APPROVED** [review]
Looks good to me. Approved.

**Pull request merged**
