### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by skyreflectedinmirrors**

### CODE REVIEW

**Comment by coleramos425** [comment]
LGTM

**Comment by feizheng10** [comment]
@skyreflectedinmirrors Do you get a chance to verify other metrics using GRBM_GUI_ACTIVE on MI300? Should some of them be replaced with $GRBM_GUI_ACTIVE_PER_XCD?

**Comment by skyreflectedinmirrors** [comment]
I believe _all_ of the YAML files that use GRBM_GUI_ACTIVE have been updated in the refactor-specs branch now.  Essentially: yes, all GRBM counts need to use the "per-xcd" version (IIRC, the only other one we use is SPI_BUSY).

**Comment by skyreflectedinmirrors** [comment]
and yes, I spot-checked them using some of my occupancy tests :)

**Comment by feizheng10** [comment]
> and yes, I spot-checked them using some of my occupancy tests :)

How about https://github.com/AMDResearch/omniperf/blob/fe3b8e06d4db2e75ea612c747eb48ccfaf31f8eb/src/omniperf_soc/analysis_configs/gfx942/0700_wavefront-launch.yaml#L137

**Comment by coleramos425** [comment]
@feizheng10 I think you're just confused because we're working out of feature branch `refactor-specs`. See here
https://github.com/AMDResearch/omniperf/blob/2bdd037a9ad68c93c28368da12f06fcca185b4a9/src/omniperf_soc/analysis_configs/gfx942/0700_wavefront-launch.yaml#L136-L142

**Comment by feizheng10** [comment]
Thanks!

**Pull request merged**
