### PR TITLE
Use proper name and icon in browser tab for Omniperf

### PR DESCRIPTION
**Pull request by xuchen-amd**
Use proper/rebranded name and icon in browser tab for Omniperf/rocprof-compute Web UI.

COMMENT:
this branch/pr is very out of date, will create a new PR based off the latest amd-staging for a cleaner PR.

### CODE REVIEW

**Comment by coleramos425** [comment]
Please format Python code using [black](https://pypi.org/project/black/), e.g.,
```shell
python3 -m pip install black
cd omniperf
black .
```

**Comment by coleramos425** [comment]
@dgaliffiAMD would you recommend we wait to merge until the naming rebrand PR to "rocprof-compute" is finalized?

**Comment by dgaliffiAMD** [comment]
> @dgaliffiAMD would you recommend we wait to merge until the naming rebrand PR to "rocprof-compute" is finalized?

Yes, I think that would be best. So, we don't confuse people with a halfway rebranded tool. :)

**Comment by coleramos425** [comment]
@xuchen-amd looks good. Same feedback as before about adding that sign-off to your commits:

image

**Pull request closed without merging**
