### PR TITLE
Unify all file handling with pathlib

### PR DESCRIPTION
**Pull request by vedithal-amd**
* Replace occurences of os.path functions with equivalent functions from
  pathlib library

* Remove unwanted imports of os.path and os

* Add coding guidelines for using pathlib instead of os.path

### CODE REVIEW

**Review by feizheng10 — APPROVED** [review]
LGTM.
Please make sure CI passed and local simple test passed.

**Review by coleramos425 — APPROVED** [review]
LGTM

**Comment by coleramos425** [comment]
@vedithal-amd once we fix the merge conflict we can squash and merge.

**Comment by vedithal-amd** [comment]
@coleramos425  I have fixed the merge conflict, once the CI has passed we can merge it

**Pull request merged**
