### PR TITLE
Spatial-multiplexing: part 1 profiling stage

### PR DESCRIPTION
**Pull request by ywang103-amd**
This PR implements multiplexing and support based in rocprof v3. CSV files from rocprof v3 are used to accelerate file parsing.

### CODE REVIEW

**Comment by benrichard-amd** [comment]
This contains changes from my Omniperf + rocprofv3 branch, https://github.com/benrichard-amd/omniperf/tree/rocprofv3, which has not been merged yet (there are two JIRA tickets we need solved first).

Please work off of my branch.

**Comment by ywang103-amd** [comment]
@benrichard-amd  so I am supposed to change the target branch to your branch in your fork?

**Comment by feizheng10** [comment]
This is just a draft PR for more code review and discussion for spatial multiplexing.
For formal PR submission, I suppose we should have separated PR just for v3 enabling from Ben's branch merged in first. @benrichard-amd would you like to create it first?

**Comment by benrichard-amd** [comment]
I will create the PR for my branch when its ready to merge. There are still two JIRA tickets blocking it.

For the multiplexing I suggest you create a PR on the latest version of my rocprofv3 branch.

**Comment by feizheng10** [comment]
> I will create the PR for my branch when its ready to merge. There are still two JIRA tickets blocking it.
> 
> For the multiplexing I suggest you create a PR on the latest version of my rocprofv3 branch.

Sure, will rebase on your latest changes.
Thanks!

**Review by feizheng10 — APPROVED** [review]

**Pull request merged**
